name = "Flywheel New Continent"
author = "CreepSean"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2376e12b8dcd12d53c118b8e32848400dfb5e9cff3e9cdd1321208f1c6c19c1b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
