name = "Flywheel New Continent"
author = "CreepSean"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62316de9792932df5bf4c5661dba071fa35c89d4050781994ed43ffef10b4a89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
