name = "Flywheel New Continent"
author = "CreepSean"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a7c65ea3445a6d2f54d6af77c33c94df2728b9675bae65b42fccf2e52ab60e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
