LootJS.lootTables(event => {
    //uncommon_tier_mob
    event
        .getLootTable("minecraft:entities/guardian")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/phantom")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/pillager")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/vindicator")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/witch")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/ghast")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/blaze")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/wither_skeleton")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/enderman")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/shulker")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:uncommon_upgrade_essence").withWeight(1).killedByPlayer())

    //rare_tier_mob
    event
        .getLootTable("minecraft:entities/iron_golem")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/elder_guardian")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/evoker")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/ravager")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("minecraft:entities/piglin_brute")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/citadel_keeper")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/archevoker")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/necromancer")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/cryomancer")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/pyromancer")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/priest")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())
    event
        .getLootTable("irons_spellbooks:entities/apothecarist")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:rare_upgrade_essence").withWeight(1).killedByPlayer())

    //epic_tier_mob
    event
        .getLootTable("minecraft:entities/warden")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:epic_upgrade_essence").randomChance(0.8))
    event
        .getLootTable("minecraft:entities/wither")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:epic_upgrade_essence").randomChance(0.8))
    event
        .getLootTable("minecraft:entities/ender_dragon")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:epic_upgrade_essence").randomChance(1))
    event
        .getLootTable("irons_spellbooks:entities/dead_king")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:epic_upgrade_essence").randomChance(1))

    //legendary_tier_mob
    event
        .getLootTable("irons_spellbooks:entities/fire_boss_per_player")
        .firstPool()
        .addEntry(LootEntry.of("fwnc:legendary_upgrade_essence").randomChance(1))

    //chest_ban
    event.clearLootTables(/.*touhou_little_maid:chest.*/)
})