ServerEvents.tags('item', event => {
    event.add('c:flours/wheat', 'tmted:wheat_flour')
    event.add('c:doughs/wheat', 'farmersdelight:wheat_dough')
    event.add('farmersdelight:tools/knives', 'tmted:steel_knife')
    event.add('farmersdelight:tools/knives', 'refurbished_furniture:knife')
    event.add('c:tools/knife', 'tmted:steel_knife')
    event.add('c:tools/knife', 'refurbished_furniture:knife')
    event.add('refurbished_furniture:tools/knives', 'tmted:steel_knife')
    event.add('refurbished_furniture:tools/knives', 'farmersdelight:flint_knife')
    event.add('refurbished_furniture:tools/knives', 'farmersdelight:iron_knife')
    event.add('refurbished_furniture:tools/knives', 'farmersdelight:diamond_knife')
    event.add('refurbished_furniture:tools/knives', 'farmersdelight:netherite_knife')
    event.add('refurbished_furniture:tools/knives', 'farmersdelight:golden_knife')
    event.add('fwnc:tier_zero_circuit', 'fwnc:mechanical_circuit')
    event.add('fwnc:tier_one_circuit', 'fwnc:early_electronic_circuit')
    event.add('fwnc:tier_two_circuit', 'fwnc:early_circuit_complex')

    event.add("curios:head",['minecolonies:build_goggles']);
})

ServerEvents.tags('fluid', event => {
    event.add('c:hamimelon_juice', 'fruitsdelight:hamimelon_juice')
    event.add('c:orange_juice', 'fruitsdelight:orange_juice')
    event.add('c:pear_juice', 'fruitsdelight:pear_juice')
    event.add('c:lemon_juice', 'fruitsdelight:lemon_juice')
    event.add('c:kiwi_juice', 'fruitsdelight:kiwi_juice')
    event.add('c:bayberry_soup', 'fruitsdelight:bayberry_soup')
    event.add('c:hawberry_tea', 'fruitsdelight:hawberry_tea')
    event.add('c:mango_tea', 'fruitsdelight:mango_tea')
    event.add('c:peach_tea', 'fruitsdelight:peach_tea')
    event.add('c:mangosteen_tea', 'fruitsdelight:mangosteen_tea')
    event.add('c:lychee_cherry_tea', 'fruitsdelight:lychee_cherry_tea')
    event.add('c:bellini_cocktail', 'fruitsdelight:bellini_cocktail')

    event.add('c:hamimelon_jello', 'fruitsdelight:hamimelon_jello')
    event.add('c:orange_jello', 'fruitsdelight:orange_jello')
    event.add('c:pear_jello', 'fruitsdelight:pear_jello')
    event.add('c:lemon_jello', 'fruitsdelight:lemon_jello')
    event.add('c:kiwi_jello', 'fruitsdelight:kiwi_jello')
    event.add('c:bayberry_jello', 'fruitsdelight:bayberry_jello')
    event.add('c:hawberry_jello', 'fruitsdelight:hawberry_jello')
    event.add('c:mango_jello', 'fruitsdelight:mango_jello')
    event.add('c:peach_jello', 'fruitsdelight:peach_jello')
    event.add('c:mangosteen_jello', 'fruitsdelight:mangosteen_jello')
    event.add('c:lychee_jello', 'fruitsdelight:lychee_jello')
    event.add('c:apple_jello', 'fruitsdelight:apple_jello')
    event.add('c:blueberry_jello', 'fruitsdelight:blueberry_jello')
    event.add('c:glowberry_jello', 'fruitsdelight:glowberry_jello')
    event.add('c:melon_jello', 'fruitsdelight:melon_jello')
    event.add('c:persimmon_jello', 'fruitsdelight:persimmon_jello')
    event.add('c:pineapple_jello', 'fruitsdelight:pineapple_jello')
    event.add('c:cranberry_jello', 'fruitsdelight:cranberry_jello')
    event.add('c:sweetberry_jello', 'fruitsdelight:sweetberry_jello')
    event.add('c:chorus_jello', 'fruitsdelight:chorus_jello')
    event.add('c:fig_jello', 'fruitsdelight:fig_jello')
    event.add('c:durian_jello', 'fruitsdelight:durian_jello')

    event.add('c:hamimelon_jam', 'fruitsdelight:hamimelon_jam')
    event.add('c:orange_jam', 'fruitsdelight:orange_jam')
    event.add('c:pear_jam', 'fruitsdelight:pear_jam')
    event.add('c:lemon_jam', 'fruitsdelight:lemon_jam')
    event.add('c:kiwi_jam', 'fruitsdelight:kiwi_jam')
    event.add('c:bayberry_jam', 'fruitsdelight:bayberry_jam')
    event.add('c:hawberry_jam', 'fruitsdelight:hawberry_jam')
    event.add('c:mango_jam', 'fruitsdelight:mango_jam')
    event.add('c:peach_jam', 'fruitsdelight:peach_jam')
    event.add('c:mangosteen_jam', 'fruitsdelight:mangosteen_jam')
    event.add('c:lychee_jam', 'fruitsdelight:lychee_jam')
    event.add('c:apple_jam', 'fruitsdelight:apple_jam')
    event.add('c:blueberry_jam', 'fruitsdelight:blueberry_jam')
    event.add('c:glowberry_jam', 'fruitsdelight:glowberry_jam')
    event.add('c:melon_jam', 'fruitsdelight:melon_jam')
    event.add('c:persimmon_jam', 'fruitsdelight:persimmon_jam')
    event.add('c:pineapple_jam', 'fruitsdelight:pineapple_jam')
    event.add('c:cranberry_jam', 'fruitsdelight:cranberry_jam')
    event.add('c:sweetberry_jam', 'fruitsdelight:sweetberry_jam')
    event.add('c:chorus_jam', 'fruitsdelight:chorus_jam')
    event.add('c:fig_jam', 'fruitsdelight:fig_jam')
    event.add('c:durian_jam', 'fruitsdelight:durian_jam')
})